"""Shared fixtures for the thread-compaction pipeline test suite.

Finalized in plan 01-01 — Wave-2 plans read these fixtures, they do not edit this file.
"""
import os
from pathlib import Path

import numpy as np
import pytest


def _find_nextcloud_root() -> Path | None:
    """Locate the synced 'threads daily imaging' folder, wherever it landed on this machine."""
    candidates = [
        os.environ.get("THREAD_DATA_ROOT", ""),
        "/home/bcjamal/Nextcloud",
        str(Path.home() / "Library/CloudStorage"),
    ]
    for root in candidates:
        if not root:
            continue
        for d in Path(root).glob("**/threads daily imaging"):
            if d.is_dir():
                return d
    return None


NEXTCLOUD_ROOT = _find_nextcloud_root()


@pytest.fixture
def sample_photo_path() -> Path:
    """A real thread photo (flat legacy convention) used for slow/integration tests."""
    if NEXTCLOUD_ROOT is None:
        pytest.skip("real sample photo not found: no 'threads daily imaging' folder located")
    path = NEXTCLOUD_ROOT / "08-03-25" / "5.11.JPG"
    if not path.exists():
        pytest.skip(f"real sample photo not found at {path}")
    return path


@pytest.fixture
def ruler_photo_path() -> Path:
    """A real ruler photo (macro/microscope shot, 0-0.5cm span) for calibration tests."""
    if NEXTCLOUD_ROOT is None:
        pytest.skip("real ruler photo not found: no 'threads daily imaging' folder located")
    path = NEXTCLOUD_ROOT / "08-03-25" / "ruler.JPG"
    if not path.exists():
        pytest.skip(f"real ruler photo not found at {path}")
    return path


@pytest.fixture
def data_root(tmp_path: Path) -> Path:
    """A pipeline-owned output directory (masks/qc/calibration/csv), never Nextcloud."""
    root = tmp_path / "data"
    for sub in ("masks", "qc", "calibration", "csv"):
        (root / sub).mkdir(parents=True, exist_ok=True)
    return root


@pytest.fixture
def synthetic_strip_mask() -> np.ndarray:
    """A boolean mask: a 20px-wide x 100px-long horizontal strip in a 120x140 field.

    Known expected width ~20px (skeleton runs along the strip's long axis; the
    distance-transform-derived diameter at any interior skeleton point should be ~20px).
    """
    mask = np.zeros((120, 140), dtype=bool)
    mask[50:70, 20:120] = True  # rows 50..69 (20px tall), cols 20..119 (100px long)
    return mask


@pytest.fixture
def ground_truth_imagej() -> dict:
    """The 4 known ImageJ ground-truth rows (Date 8/1/25) for loose sanity checks.

    Only 4 rows exist — this is a plausibility check, not a strict statistical validation
    (per user: "just for the purposes of output fields and sanity measurements").
    """
    return {
        "5.11": {"avg_diameter_mm": 0.788911937, "stdev_mm": 0.11124384},
        "5.12": {"avg_diameter_mm": 0.865211023, "stdev_mm": 0.10093196},
        "5.21": {"avg_diameter_mm": 0.858229612, "stdev_mm": 0.09995796},
        "5.22": {"avg_diameter_mm": 0.932637245, "stdev_mm": None},
    }
